### ISSUE TITLE
SW Development

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-COM#2]
* [x] Port DRAPRS v4 Firmware #6 
* [ ] Remove unnecessary SW components #7 
* [ ] Add Time MGMT #8 
* [ ] Add UPRA-SICL #9 
* [ ] Add RF PWR MGMT #10 
* [ ] Add Telemetry #11 #12
