### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-COM#3]
* [ ] Build TestLink environment #14 
* [ ] EM Breadboard assembly #15 
* [ ] Unit Tests #16 
* [ ] Module Integration Tests #17 
* [ ] UHF-VHF Integration Tests #18 
* [ ] System Integration Tests #19 
* [ ] Thermal Tests #20 
* [ ] Field Tests #21
